# Generated by Django 4.2.3 on 2023-07-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creater", models.CharField(max_length=255)),
                ("profile_pic", models.ImageField(null=True, upload_to="profile_pic/")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("content_text", models.TextField()),
                ("likers", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
