# Generated by Django 4.2.3 on 2023-07-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
