# Generated by Django 4.2.3 on 2023-07-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0005_comment_parent_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="commenter_pic",
            field=models.ImageField(null=True, upload_to="commenter_pic/"),
        ),
    ]
