# Generated by Django 4.2.3 on 2023-07-21 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_picture", models.ImageField(upload_to="profile_pictures/")),
                ("bio", models.TextField(blank=True, max_length=160)),
                ("cover_image1", models.ImageField(upload_to="cover_images/")),
                ("cover_image2", models.ImageField(upload_to="cover_images/")),
                ("mobile_number", models.CharField(max_length=20)),
                ("mobile_visible", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
