# Generated by Django 4.2.1 on 2023-08-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_userprofile_cover_image2_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="fullname",
            field=models.CharField(default="", max_length=100),
        ),
    ]
