# Generated by Django 4.2.1 on 2023-08-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_userprofile_fullname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="gender",
        ),
    ]
